### ISSUE TITLE
java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage

### ISSUE THREAD

**Issue by stuzocub** [chocovon/debug-variable-extractor#3]
java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage

Version of Intellij IntelliJ IDEA 2024.3 (Community Edition)
windows 10

**Comment by chocovon** [comment]
The plugin is not working in 2024.3. I've mistakenly set the compatibility range, sorry for that.

I'll try to make an upgrade for it later if I got time.

**Comment by chocovon** [comment]
The fix is done and new version is under reviewing.

**Comment by stuzocub** [comment]
Thanks

**Comment by chocovon** [comment]
It's available now in 2024.3.
